package com.kabir.onlinestoremanagementsystem.domain;
// Generated Jul 28, 2018 1:01:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name="order_items"
    ,catalog="online_store_management"
)
public class OrderItems  implements java.io.Serializable {


     private Integer orderItemsId;
     private Customer customer;
     private Orders orders;
     private Product product;
     private double price;
     private int quantity;
     private double discountPrice;
     private double totalPrice;
     private double netPrice;
     private String delivaryZone;
     private String address;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public OrderItems() {
    }

	
    public OrderItems(Customer customer, Orders orders, Product product, double price, int quantity, double discountPrice, double totalPrice, double netPrice, String delivaryZone, String address) {
        this.customer = customer;
        this.orders = orders;
        this.product = product;
        this.price = price;
        this.quantity = quantity;
        this.discountPrice = discountPrice;
        this.totalPrice = totalPrice;
        this.netPrice = netPrice;
        this.delivaryZone = delivaryZone;
        this.address = address;
    }
    public OrderItems(Customer customer, Orders orders, Product product, double price, int quantity, double discountPrice, double totalPrice, double netPrice, String delivaryZone, String address, Set<Payment> payments) {
       this.customer = customer;
       this.orders = orders;
       this.product = product;
       this.price = price;
       this.quantity = quantity;
       this.discountPrice = discountPrice;
       this.totalPrice = totalPrice;
       this.netPrice = netPrice;
       this.delivaryZone = delivaryZone;
       this.address = address;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_items_id", unique=true, nullable=false)
    public Integer getOrderItemsId() {
        return this.orderItemsId;
    }
    
    public void setOrderItemsId(Integer orderItemsId) {
        this.orderItemsId = orderItemsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="discount_price", nullable=false, precision=22, scale=0)
    public double getDiscountPrice() {
        return this.discountPrice;
    }
    
    public void setDiscountPrice(double discountPrice) {
        this.discountPrice = discountPrice;
    }

    
    @Column(name="total_price", nullable=false, precision=22, scale=0)
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    
    @Column(name="net_price", nullable=false, precision=22, scale=0)
    public double getNetPrice() {
        return this.netPrice;
    }
    
    public void setNetPrice(double netPrice) {
        this.netPrice = netPrice;
    }

    
    @Column(name="delivary_zone", nullable=false, length=45)
    public String getDelivaryZone() {
        return this.delivaryZone;
    }
    
    public void setDelivaryZone(String delivaryZone) {
        this.delivaryZone = delivaryZone;
    }

    
    @Column(name="address", nullable=false, length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orderItems")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


