package com.kabir.onlinestoremanagementsystem.domain;
// Generated Jul 28, 2018 1:01:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="online_store_management"
)
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private Customer customer;
     private Product product;
     private Date createDate;
     private String orderStatus;
     private int orderSubTotal;
     private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

    public Orders() {
    }

	
    public Orders(Customer customer, Product product, Date createDate, String orderStatus, int orderSubTotal) {
        this.customer = customer;
        this.product = product;
        this.createDate = createDate;
        this.orderStatus = orderStatus;
        this.orderSubTotal = orderSubTotal;
    }
    public Orders(Customer customer, Product product, Date createDate, String orderStatus, int orderSubTotal, Set<OrderItems> orderItemses) {
       this.customer = customer;
       this.product = product;
       this.createDate = createDate;
       this.orderStatus = orderStatus;
       this.orderSubTotal = orderSubTotal;
       this.orderItemses = orderItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="create_date", nullable=false, length=10)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="order_status", nullable=false, length=45)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    
    @Column(name="order_sub_total", nullable=false)
    public int getOrderSubTotal() {
        return this.orderSubTotal;
    }
    
    public void setOrderSubTotal(int orderSubTotal) {
        this.orderSubTotal = orderSubTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrderItems> getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set<OrderItems> orderItemses) {
        this.orderItemses = orderItemses;
    }




}


