package com.kabir.onlinestoremanagementsystem.domain;
// Generated Jul 28, 2018 1:01:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="online_store_management"
)
public class Payment  implements java.io.Serializable {


     private Integer paymentId;
     private Customer customer;
     private OrderItems orderItems;
     private String paymentStatus;
     private Date paymentDate;
     private double totalPayment;
     private double discount;
     private String paymentType;
     private double delivaryCharge;

    public Payment() {
    }

    public Payment(Customer customer, OrderItems orderItems, String paymentStatus, Date paymentDate, double totalPayment, double discount, String paymentType, double delivaryCharge) {
       this.customer = customer;
       this.orderItems = orderItems;
       this.paymentStatus = paymentStatus;
       this.paymentDate = paymentDate;
       this.totalPayment = totalPayment;
       this.discount = discount;
       this.paymentType = paymentType;
       this.delivaryCharge = delivaryCharge;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_id", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_items_id", nullable=false)
    public OrderItems getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(OrderItems orderItems) {
        this.orderItems = orderItems;
    }

    
    @Column(name="payment_status", nullable=false, length=100)
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="payment_date", nullable=false, length=10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="total_payment", nullable=false, precision=22, scale=0)
    public double getTotalPayment() {
        return this.totalPayment;
    }
    
    public void setTotalPayment(double totalPayment) {
        this.totalPayment = totalPayment;
    }

    
    @Column(name="discount", nullable=false, precision=22, scale=0)
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }

    
    @Column(name="payment_type", nullable=false, length=45)
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    
    @Column(name="delivary_charge", nullable=false, precision=22, scale=0)
    public double getDelivaryCharge() {
        return this.delivaryCharge;
    }
    
    public void setDelivaryCharge(double delivaryCharge) {
        this.delivaryCharge = delivaryCharge;
    }




}


