package com.kabir.onlinestoremanagementsystem.domain;
// Generated Jul 28, 2018 1:01:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProSubCategory generated by hbm2java
 */
@Entity
@Table(name="pro_sub_category"
    ,catalog="online_store_management"
)
public class ProSubCategory  implements java.io.Serializable {


     private Integer subCategoryId;
     private ProCategory proCategory;
     private String subCategoryName;
     private String description;
     private Set<Product> products = new HashSet<Product>(0);

    public ProSubCategory() {
    }

	
    public ProSubCategory(ProCategory proCategory, String subCategoryName, String description) {
        this.proCategory = proCategory;
        this.subCategoryName = subCategoryName;
        this.description = description;
    }
    public ProSubCategory(ProCategory proCategory, String subCategoryName, String description, Set<Product> products) {
       this.proCategory = proCategory;
       this.subCategoryName = subCategoryName;
       this.description = description;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sub_category_id", unique=true, nullable=false)
    public Integer getSubCategoryId() {
        return this.subCategoryId;
    }
    
    public void setSubCategoryId(Integer subCategoryId) {
        this.subCategoryId = subCategoryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public ProCategory getProCategory() {
        return this.proCategory;
    }
    
    public void setProCategory(ProCategory proCategory) {
        this.proCategory = proCategory;
    }

    
    @Column(name="sub_category_name", nullable=false, length=100)
    public String getSubCategoryName() {
        return this.subCategoryName;
    }
    
    public void setSubCategoryName(String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }

    
    @Column(name="description", nullable=false, length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proSubCategory")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


